=== thomasgreb/Lebovka-et-al_cambium-models/model_1_to_3C_framework/VirtualLeaf-v1.0/data/leaves/vleaf.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- 
  $Rev: 79f94eaa3b9e $:  Revision of last commit
  $Author: michael $:  Author of last commit
  $Source: vleaf.xsd $:  Source file
  $Date: 2010/04/14 05:51:02 $:  Date of last commit

  This file is part of the Virtual Leaf.

  The Virtual Leaf is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  The Virtual Leaf is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with the Virtual Leaf.  If not, see <http://www.gnu.org/licenses/>.

  Copyright 2010 Michael Guravage.
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="vl" targetNamespace="vl"
    elementFormDefault="qualified" attributeFormDefault="unqualified">

    <xs:annotation>
        <xs:documentation> Virtual Leaf </xs:documentation>
    </xs:annotation>

    <!-- A precooked comment element -->
    <xs:element name="comment" type="xs:string"/>



    <!-- An element with a integer value named 'v.' -->
    <xs:complexType name="iValueType">
        <xs:attribute name="v" type="xs:integer"/>
    </xs:complexType>



    <!-- An element with a real value named 'v.' -->
    <xs:complexType name="rValueType">
        <xs:attribute name="v" type="xs:float"/>
    </xs:complexType>



    <!-- Leaf is the root element -->
    <xs:element name="leaf">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="comment" minOccurs="0"/>
                <xs:element name="parameter" type="ParameterType" minOccurs="0"/>
                <xs:element name="code" type="CodeType" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="nodes" type="NodesType" minOccurs="0"/>
                <xs:element name="cells" type="CellsType" minOccurs="0"/>
                <xs:element name="walls" type="WallsType" minOccurs="0"/>
                <xs:element name="nodesets" type="NodesetsType" minOccurs="0"/>
                <xs:element name="settings" type="SettingsType" minOccurs="0"/>
            </xs:sequence>
            <xs:attributeGroup ref="leafAttrubutes"/>
        </xs:complexType>
    </xs:element>

    <!-- List of leaf attributes -->
    <xs:attributeGroup name="leafAttrubutes">
        <xs:attribute name="uri" type="xs:anyURI"/>
        <xs:attribute name="date" type="xs:dateTime"/>
        <xs:attribute name="simtime" type="xs:integer"/>
    </xs:attributeGroup>



    <!-- Parameters -->
    <xs:complexType name="ParameterType">
        <xs:sequence>
            <xs:element name="comment" minOccurs="0"/>
            <xs:element name="par" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="valarray" minOccurs="0">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="val" type="rValueType" maxOccurs="unbounded"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="name" type="xs:string" use="required"/>
                    <xs:attribute name="val" type="xs:string"/>
                    <xs:anyAttribute processContents="skip"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>


    <!-- Code -->
    <xs:complexType name="CodeType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>



    <!-- Nodes -->
    <xs:complexType name="NodesType">
        <xs:sequence>
            <xs:element name="comment" minOccurs="0"/>
            <xs:element name="node" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attributeGroup ref="nodeAttributes"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attributeGroup ref="nodesAttributes"/>
    </xs:complexType>

    <!-- A list of node attributes -->
    <xs:attributeGroup name="nodeAttributes">
        <xs:attribute name="x" type="xs:float" use="required"/>
        <xs:attribute name="y" type="xs:float" use="required"/>
        <xs:attribute name="fixed" type="xs:boolean"/>
        <xs:attribute name="boundary" type="xs:boolean"/>
        <xs:attribute name="sam" type="xs:boolean"/>
    </xs:attributeGroup>

    <!-- A list of nodes attributes -->
    <xs:attributeGroup name="nodesAttributes">
        <xs:attribute name="n" type="xs:integer" use="required"/>
        <xs:attribute name="target_length" type="xs:float" use="required"/>
    </xs:attributeGroup>



    <!-- Cells -->
    <xs:complexType name="CellsType">
        <xs:sequence>
            <xs:element name="comment" minOccurs="0"/>
            <xs:element name="cell" type="CellType" maxOccurs="unbounded"/>
            <xs:element name="boundary_polygon" type="CellType"/>
        </xs:sequence>
        <xs:attributeGroup ref="cellsAttributes"/>
    </xs:complexType>

    <!-- A list of cells attributes and their types -->
    <xs:attributeGroup name="cellsAttributes">
        <xs:attribute name="n" type="xs:integer" use="required"/>
        <xs:attribute name="offsetx" type="xs:float"/>
        <xs:attribute name="offsety" type="xs:float"/>
        <xs:attribute name="magnification" type="xs:float"/>
        <xs:attribute name="base_area" type="xs:float" use="required"/>
        <xs:attribute name="nchem" type="xs:integer" use="required"/>
    </xs:attributeGroup>

    <!-- Cell -->
    <xs:complexType name="CellType">
        <xs:sequence>
            <xs:element name="node" type="CellNodeType"  minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="wall" type="CellWallType"  minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="chem" type="CellChemType" minOccurs="0"/>
        </xs:sequence>
        <xs:attributeGroup ref="cellAttributes"/>
    </xs:complexType>

    <!-- A list of cell attributes and their types. -->
    <xs:attributeGroup name="cellAttributes">
        <xs:attribute name="index" type="xs:integer" use="required"/>
        <xs:attribute name="area" type="xs:float"/>
        <xs:attribute name="target_area" type="xs:float" use="required"/>
        <xs:attribute name="target_length" type="xs:float"/>
        <xs:attribute name="lambda_celllength" type="xs:float"/>
        <xs:attribute name="stiffness" type="xs:float"/>
        <xs:attribute name="fixed" type="xs:boolean"/>
        <xs:attribute name="pin_fixed" type="xs:boolean"/>
        <xs:attribute name="at_boundary" type="xs:boolean"/>
        <xs:attribute name="dead" type="xs:boolean"/>
        <xs:attribute name="source" type="xs:boolean"/>
        <xs:attribute name="boundary" type="xs:boolean"/>
        <xs:attribute name="div_counter" type="xs:integer"/>
        <xs:attribute name="cell_type" type="xs:integer"/>
    </xs:attributeGroup>

    <!-- Cell Node -->
    <xs:complexType name="CellNodeType">
        <xs:attribute name="n" type="xs:integer" use="required"/>
    </xs:complexType>

    <!-- Cell Wall -->
    <xs:complexType name="CellWallType">
        <xs:attribute name="w" type="xs:integer" use="required"/>
    </xs:complexType>

    <!-- Cell Chemical -->
    <xs:complexType name="CellChemType">
        <xs:sequence>
            <xs:element name="val" type="rValueType"  minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="n" type="xs:integer" use="required"/>
    </xs:complexType>



    <!-- Walls  -->
    <xs:complexType name="WallsType">
        <xs:sequence>
            <xs:element name="comment" minOccurs="0"/>
            <xs:element name="wall" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="transporter1" minOccurs="0">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="val" type="rValueType" minOccurs="0" maxOccurs="unbounded"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="transporter2" minOccurs="0">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="val" type="rValueType" minOccurs="0" maxOccurs="unbounded"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="apoplast" minOccurs="0">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="val" type="rValueType" minOccurs="0" maxOccurs="unbounded"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="index" type="xs:integer" use="required"/>
                    <xs:attribute name="c1" type="xs:integer" use="required"/>
                    <xs:attribute name="c2" type="xs:integer" use="required"/>
                    <xs:attribute name="n1" type="xs:integer" use="required"/>
                    <xs:attribute name="n2" type="xs:integer" use="required"/>
                    <xs:attribute name="length" type="xs:float"/>
                    <xs:attribute name="viz_flux" type="xs:integer"/>
                    <xs:attribute name="wall_type">
                        <xs:simpleType>
                            <xs:restriction base="xs:normalizedString">
                                <xs:enumeration value="normal"/>
                                <xs:enumeration value="aux_source"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="n" type="xs:integer" use="required"/>
    </xs:complexType>



    <!-- Nodesets -->
    <xs:complexType name="NodesetsType">
        <xs:attribute name="n" type="xs:integer" use="required"/>
    </xs:complexType>



    <!-- Settings -->
    <xs:complexType name="SettingsType">
        <xs:sequence>
            <xs:element name="comment" minOccurs="0"/>
            <xs:element name="setting" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="name" type="xs:string" use="required"/>
                    <xs:attribute name="val" type="xs:boolean" use="required"/>
                    <xs:anyAttribute processContents="skip"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== thomasgreb/Lebovka-et-al_cambium-models/model_1_to_3C_framework/VirtualLeaf-v1.0/data/leaves/vleaf.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- 
  $Rev: 79f94eaa3b9e $:  Revision of last commit
  $Author: michael $:  Author of last commit
  $Source: vleaf.xml $:  Source File
  $Date: 2010/04/14 05:51:02 $:  Date of last commit

  This file is part of the Virtual Leaf.

  The Virtual Leaf is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  The Virtual Leaf is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with the Virtual Leaf.  If not, see <http://www.gnu.org/licenses/>.

  Copyright 2010 Roeland Merks.
-->

<leaf  uri="file://Users/roel/VLeafMacOSX/vleaf.xml" 
       simtime="12140" 
       date="2009-10-08T17:41:39" 
       xmlns="vl" 
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="vl file:/ufs/guravage/.archive/mas/vleaf/src/vleaf.xsd">
  <comment/>
  <parameter>
    <comment></comment>
    <par name="arrowcolor" val="white"/>
    <par name="arrowsize" val="10"/>
    <par name="textcolor" val="red"/>
    <par name="cellnumsize" val="1"/>
    <par name="nodenumsize" val="1"/>
    <par name="node_mag" val="1"/>
    <par name="outlinewidth" val="1"/>
    <par name="cell_outline_color" val="forestgreen"/>
    <par name="resize_stride" val="10"/>
    <par name="T" val="1"/>
    <par name="lambda_length" val="100"/>
    <par name="lambda_celllength" val="0"/>
    <par name="target_length" val="60"/>
    <par name="cell_expansion_rate" val="10"/>
    <par name="cell_div_expansion_rate" val="10"/>
    <par name="auxin_dependent_growth" val="true"/>
    <par name="ode_accuracy" val="0.0001"/>
    <par name="mc_stepsize" val="0.4"/>
    <par name="mc_cell_stepsize" val="0.2"/>
    <par name="energy_threshold" val="1000"/>
    <par name="bend_lambda" val="0"/>
    <par name="alignment_lambda" val="0"/>
    <par name="rel_cell_div_threshold" val="2"/>
    <par name="rel_perimeter_stiffness" val="2"/>
    <par name="collapse_node_threshold" val="0.05"/>
    <par name="morphogen_div_threshold" val="0.2"/>
    <par name="morphogen_expansion_threshold" val="0.01"/>
    <par name="copy_wall" val="true"/>
    <par name="source" val="0"/>
    <par name="D">
      <valarray>
        <val v="1e-06"/>
        <val v="0"/>
        <val v="0"/>
        <val v="0"/>
      </valarray>
    </par>
    <par name="initval">
      <valarray>
        <val v="0"/>
        <val v="1"/>
        <val v="0"/>
        <val v="0"/>
      </valarray>
    </par>
    <par name="k1" val="1"/>
    <par name="k2" val="0.3"/>
    <par name="r" val="1"/>
    <par name="kr" val="1"/>
    <par name="km" val="1"/>
    <par name="Pi_tot" val="1"/>
    <par name="transport" val="0.36"/>
    <par name="ka" val="1"/>
    <par name="pin_prod" val="0"/>
    <par name="pin_prod_in_epidermis" val="0"/>
    <par name="pin_breakdown" val="0"/>
    <par name="pin_breakdown_internal" val="0.001"/>
    <par name="aux1prod" val="0.001"/>
    <par name="aux1prodmeso" val="0"/>
    <par name="aux1decay" val="0.001"/>
    <par name="aux1decaymeso" val="0.1"/>
    <par name="aux1transport" val="0.036"/>
    <par name="aux_cons" val="0"/>
    <par name="aux_breakdown" val="0.0001"/>
    <par name="kaux1" val="1"/>
    <par name="kap" val="1"/>
    <par name="leaf_tip_source" val="0.0001"/>
    <par name="sam_efflux" val="0.0001"/>
    <par name="sam_auxin" val="10"/>
    <par name="sam_auxin_breakdown" val="0"/>
    <par name="dt" val="0.1"/>
    <par name="rd_dt" val="10"/>
    <par name="datadir" val="auxin_growth"/>
    <par name="movie" val="true"/>
    <par name="nit" val="100000"/>
    <par name="maxt" val="1e+06"/>
    <par name="storage_stride" val="10"/>
    <par name="xml_storage_stride" val="500"/>
    <par name="rseed" val="-1"/>
    <par name="constituous_expansion_limit" val="16"/>
    <par name="vessel_inh_level" val="1"/>
    <par name="vessel_expansion_rate" val="0.25"/>
    <par name="d" val="0"/>
    <par name="e" val="0"/>
    <par name="f" val="0"/>
    <par name="c" val="0"/>
    <par name="mu" val="0"/>
    <par name="nu" val="0"/>
    <par name="rho0" val="0"/>
    <par name="rho1" val="0"/>
    <par name="c0" val="0"/>
    <par name="gamma" val="0"/>
    <par name="eps" val="0"/>
  </parameter>
  <code name="VirtualLeaf.cpp">#include &lt;fstream&gt;
#include &lt;sstream&gt;
#include &lt;cstring&gt;
#include &lt;functional&gt; 
#include &lt;getopt.h&gt;
#include &lt;cerrno&gt;
#include "mesh.h"
#include "parameter.h"
#include "random.h"
#include "pi.h"
#include "cellitem.h"
#include "canvas.h"
#include "cell.h"
#include "output.h"
#include &lt;qwidget.h&gt;
#include &lt;q3process.h&gt;
#include &lt;qapplication.h&gt;
#include &lt;QDesktopWidget&gt;
#include &lt;QGraphicsScene&gt;
#include &lt;QMessageBox&gt;
//Added by qt3to4:
#include &lt;QMouseEvent&gt;

#include &lt;unistd.h&gt;
#include &lt;q3textstream.h&gt; 


#ifdef HAVE_QWT
#include "data_plot.h"
#endif
#include &lt;QPalette&gt;
#include &lt;QBrush&gt;
#include &lt;QToolTip&gt;
#include "simplugin.h"
#include "testplugin.h"

/* #define _xstr_(s) _str_(s)
#define _str_(s) #s
#include _xstr_(REACTIONS_HEADER)
*/
extern Parameter par;

MainBase *main_window = 0;
double auxin_account = 0.;



TestPlugin *plugin = new TestPlugin();

#ifdef XFIGGRAPHICS
#define TIMESTEP double Graphics::TimeStep(void)
#endif

class PrintNode {
public:
  void operator() (const Node &amp;n) const 
  {
    cerr &lt;&lt; n.Index() &lt;&lt; ": " &lt;&lt; n &lt;&lt;  endl;
  }
};


class EdgeSource {
	
public:
  void operator() (Cell &amp;c) {
		
    if (c.AtBoundaryP()) {
      cerr &lt;&lt; "Cell " &lt;&lt; c.Index() &lt;&lt; " is a source cell.\n";
      c.SetSource(0,par.source);
    } else {
      cerr &lt;&lt; "Cell " &lt;&lt; c.Index() &lt;&lt; " is _not_ a source cell.\n";
    }
  }
	
};



class CellInfo {
public:
  void operator() (Cell &amp;c,std::ostream &amp;os) const {
    os &lt;&lt; "Cell " &lt;&lt; c.index &lt;&lt; " says: " &lt;&lt; endl;
    os &lt;&lt; "c.nodes.size() = " &lt;&lt; c.nodes.size() &lt;&lt; endl;
    for (list&lt;Node *&gt;::iterator i=c.nodes.begin();
	 i!=c.nodes.end();
	 i++) {
      cerr &lt;&lt; (*i)-&gt;Index() &lt;&lt; " ";
    }
    cerr &lt;&lt; endl;
  }
};

double PINSum(Cell &amp;c) {
	
	return c.Chemical(1) + c.SumTransporters(1);// + c.ReduceCellAndWalls&lt;double&gt;( complex_PijAj );
	
}


class DrawCell {
public:
  void operator() (Cell &amp;c,QGraphicsScene &amp;canvas, MainBase &amp;m) const {
    if (m.ShowBorderCellsP() || c.Boundary()==Cell::None) {
      if (!m.ShowBoundaryOnlyP() &amp;&amp; !m.HideCellsP()) 
	if (m.ShowToolTipsP()) {
	  QString info_string=QString("Cell %1, chemicals: ( %2, %3, %4, %5, %6)\n %7 of PIN1 at walls.\n Area is %8\n PIN sum is %9\n Circumference is %10\n Boundary type is %11").arg(c.Index()).arg(c.Chemical(0)).arg(c.Chemical(1)).arg(c.Chemical(2)).arg(c.Chemical(3)).arg(c.Chemical(4)).arg(c.SumTransporters(1)).arg(c.Area()).arg(PINSum(c)).arg(c.Circumference()).arg(c.BoundaryStr());
					
	  info_string += "\n" + c.printednodelist();
					
	  c.Draw(&amp;canvas, info_string);
	} else {
	  c.Draw(&amp;canvas);
	}
      if (m.ShowCentersP())
	c.DrawCenter(&amp;canvas);
    if (m.ShowFluxesP())
	c.DrawFluxes(&amp;canvas, par.arrowsize);
			
       }
 
  }
	
};

Mesh mesh;
bool batch=false;


void MainBase::Plot(int resize_stride) {
	
  clear();
    
	
  static int count=0;
  if (resize_stride) {
    if ( !((++count)%resize_stride) ) {
      FitLeafToCanvas();
    }
  }
  mesh.LoopCells(DrawCell(),canvas,*this);
	
  if (ShowNodeNumbersP()) 
    mesh.LoopNodes( bind2nd (mem_fun_ref ( &amp;Node::DrawIndex), &amp;canvas ) ) ;
  if (ShowCellNumbersP()) 
    mesh.LoopCells( bind2nd (mem_fun_ref ( &amp;Cell::DrawIndex), &amp;canvas ) ) ;
	
  if (ShowCellAxesP()) 
    mesh.LoopCells( bind2nd (mem_fun_ref ( &amp;Cell::DrawAxis), &amp;canvas ) );
	
  if (ShowCellStrainP()) 
    mesh.LoopCells( bind2nd (mem_fun_ref ( &amp;Cell::DrawStrain), &amp;canvas ) );
	
  if (ShowWallsP())
  
    mesh.LoopWalls( bind2nd( mem_fun_ref( &amp;Wall::Draw ), &amp;canvas ) );
	
	if (ShowApoplastsP()) 
		mesh.LoopWalls( bind2nd( mem_fun_ref( &amp;Wall::DrawApoplast ), &amp;canvas ) );
 
	if (ShowMeshP()) 
    mesh.DrawNodes(&amp;canvas);
	
  if (ShowBoundaryOnlyP()) 
    mesh.DrawBoundary(&amp;canvas);

  
	if ( ( batch || MovieFramesP() )) {
		
		static int frame = 0;
		// frame numbers are sequential for the most frequently written file type.
		// for the less frequently written file type they match the other type
		if (!(count%par.storage_stride) )  {
		
			stringstream fname;
			fname &lt;&lt; par.datadir &lt;&lt; "/leaf.";
			fname.fill('0');
			fname.width(6);
	
			/* 
			 fname &lt;&lt; frame &lt;&lt; ".pdf";
			if (par.storage_stride &lt;= par.xml_storage_stride) {
				frame++;
			}
			
			// Write high-res JPG snapshot every plot step
			Save(fname.str().c_str(), "PDF");
			*/
			
			fname &lt;&lt; frame &lt;&lt; ".jpg";
			if (par.storage_stride &lt;= par.xml_storage_stride) {
				frame++;
			}
			
			// Write high-res JPG snapshot every plot step
			Save(fname.str().c_str(), "JPEG",1024,768);
			
		}
	
		if (!(count%par.xml_storage_stride)) {
			stringstream fname;
			fname &lt;&lt; par.datadir &lt;&lt; "/leaf.";
			fname.fill('0');
			fname.width(6);
			fname &lt;&lt; frame &lt;&lt; ".xml";
	
			if (par.xml_storage_stride &lt; par.storage_stride) {
				frame++;
			}
			// Write XML file every ten plot steps
			mesh.XMLSave(fname.str().c_str(), XMLSettingsTree());
		}
		
	}
}


void Cell::Flux(double *flux, double *D)  {
	

  // loop over cell edges
